# {name} - Bukkit Plugin configuration file
# Copyright © {copyright.years} Visual Illusions Entertainment
# Licensed under the {gpl.type}
name: {name}
version: {plugin.version}
main: {bukkit.main.class}
author: Visual Illusions Entertainment
website: {wiki}
soft-depend: [Vault]

commands:
  realms:
    description: Realms base command. Use /realms help for sub command help.
    usage: /realms <subcommand> <subargs>

permissions:
  realms.admin:
    description: Gives access to the Realms administration commands (configreload/reloadzone/givemepermission)
    default: op

